import { createFileRoute, Link, useNavigate } from "@tanstack/react-router";
import { motion } from "framer-motion";
import { Button } from "@/components/ui/button";
import { Navbar } from "@/components/Navbar";
import { FileText, Sparkles, TrendingUp, GraduationCap, ArrowRight, CheckCircle2, Circle } from "lucide-react";

export const Route = createFileRoute("/")({
  component: Landing,
});

const features = [
  { icon: FileText, title: "PDF parsing", desc: "Drop any exam PDF — we extract the text and structure automatically." },
  { icon: Sparkles, title: "AI explanations", desc: "Every answer comes with a clear explanation generated by AI." },
  { icon: TrendingUp, title: "Progress tracking", desc: "See your best scores, attempt history, and improvement over time." },
  { icon: GraduationCap, title: "TCS iON support", desc: "Optimized for competitive exam papers and assessment formats." },
];

function Landing() {
  const navigate = useNavigate();
  return (
    <div className="min-h-screen bg-background">
      <Navbar />

      {/* Hero */}
      <section className="relative overflow-hidden">
        <div className="absolute inset-0 gradient-hero" />
        <div className="absolute inset-0 grid-bg" />
        <div className="relative mx-auto grid max-w-7xl gap-12 px-4 pb-24 pt-20 sm:px-6 lg:grid-cols-[1.15fr_1fr] lg:gap-8 lg:pt-28">
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.6, ease: "easeOut" }}
          >
            <div className="inline-flex items-center gap-2 rounded-full border border-primary/30 bg-primary/10 px-3 py-1 text-xs font-medium text-primary">
              <Sparkles className="h-3 w-3" /> AI-powered MCQ generation
            </div>
            <h1 className="mt-6 font-display text-5xl font-bold leading-[1.05] tracking-tight text-foreground sm:text-6xl lg:text-7xl">
              Turn any exam PDF into an{" "}
              <span className="text-gradient">interactive quiz</span>
            </h1>
            <p className="mt-6 max-w-xl text-lg text-muted-foreground">
              Upload a study guide, past paper, or chapter notes. Quizify extracts multiple choice questions, generates explanations, and tracks your progress — all in seconds.
            </p>
            <div className="mt-8 flex flex-wrap gap-3">
              <Button variant="hero" size="xl" onClick={() => navigate({ to: "/register" })}>
                Get started free <ArrowRight className="h-4 w-4" />
              </Button>
              <Button variant="outline" size="xl" onClick={() => navigate({ to: "/login" })}>
                Sign in
              </Button>
            </div>
            <div className="mt-8 flex items-center gap-6 text-sm text-muted-foreground">
              <span className="flex items-center gap-2"><CheckCircle2 className="h-4 w-4 text-primary" /> Free to start</span>
              <span className="flex items-center gap-2"><CheckCircle2 className="h-4 w-4 text-primary" /> No credit card</span>
            </div>
          </motion.div>

          {/* Floating mockup */}
          <motion.div
            initial={{ opacity: 0, scale: 0.95, y: 30 }}
            animate={{ opacity: 1, scale: 1, y: 0 }}
            transition={{ duration: 0.7, delay: 0.2, ease: "easeOut" }}
            className="relative"
          >
            <div className="absolute -inset-6 rounded-3xl bg-primary/20 blur-3xl" />
            <div className="animate-float relative rounded-2xl border border-white/10 gradient-card p-6 shadow-elevated">
              <div className="mb-5 flex items-center justify-between text-xs text-muted-foreground">
                <span>Question 3 of 10</span>
                <span className="rounded-full bg-primary/15 px-2 py-0.5 text-primary">02:14</span>
              </div>
              <div className="mb-2 h-1.5 w-full overflow-hidden rounded-full bg-white/5">
                <div className="h-full w-[30%] gradient-primary" />
              </div>
              <h3 className="mt-6 font-display text-lg font-semibold text-foreground">
                Which sorting algorithm has the best average-case time complexity?
              </h3>
              <div className="mt-5 space-y-2.5">
                {[
                  { t: "Bubble Sort", s: false },
                  { t: "Quick Sort", s: true },
                  { t: "Insertion Sort", s: false },
                  { t: "Selection Sort", s: false },
                ].map((o, i) => (
                  <div
                    key={i}
                    className={`flex items-center gap-3 rounded-xl border px-4 py-3 text-sm transition-colors ${
                      o.s
                        ? "border-primary/60 bg-primary/10 text-foreground"
                        : "border-border bg-surface-elevated/40 text-muted-foreground"
                    }`}
                  >
                    {o.s ? <CheckCircle2 className="h-4 w-4 text-primary" /> : <Circle className="h-4 w-4" />}
                    {o.t}
                  </div>
                ))}
              </div>
            </div>
          </motion.div>
        </div>
      </section>

      {/* Features */}
      <section className="mx-auto max-w-7xl px-4 py-20 sm:px-6">
        <div className="mb-12 max-w-2xl">
          <h2 className="font-display text-3xl font-bold tracking-tight sm:text-4xl">
            Everything you need to study smarter
          </h2>
          <p className="mt-3 text-muted-foreground">
            Built for students, exam-takers, and lifelong learners.
          </p>
        </div>
        <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">
          {features.map((f, i) => (
            <motion.div
              key={f.title}
              initial={{ opacity: 0, y: 20 }}
              whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: true }}
              transition={{ duration: 0.4, delay: i * 0.08 }}
              whileHover={{ y: -4 }}
              className="group rounded-2xl border border-border gradient-card p-6 shadow-card transition-all duration-300 hover:border-primary/40 hover:shadow-elevated"
            >
              <div className="mb-4 grid h-11 w-11 place-items-center rounded-xl bg-primary/15 text-primary transition-transform group-hover:scale-110">
                <f.icon className="h-5 w-5" />
              </div>
              <h3 className="font-display text-base font-semibold">{f.title}</h3>
              <p className="mt-2 text-sm text-muted-foreground">{f.desc}</p>
            </motion.div>
          ))}
        </div>
      </section>

      <footer className="border-t border-border py-10 text-center text-xs text-muted-foreground">
        Built with Quizify · <Link to="/login" className="hover:text-foreground">Sign in</Link>
      </footer>
    </div>
  );
}
